name: Hello world CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Print message
        run: |
            echo "hello world, this is a sample ci/cd"
            
